[[main]]
  name = "Home"
  url = ""
  weight = -110

#[[main]]
#  name = "Archives"
#  url = "post/rich-content/"
#  weight = -109

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Links"
  identifier = "Links"
  weight = -108
[[main]]
  parent = "Links"
  name = "SPIMS"
  url = "http://spimsv2.sprobe.ph/index.php/site/login"
[[main]]
  parent = "Links"
  name = "Phabricator"
  url = "https://phabricator.sprobe.ph"
[[main]]
  parent = "Links"
  name = "SkillsBase"
  url = "https://phabricator.sprobe.ph"

#[[main]]
#  name = "About"
#  url = "about/"
#  weight = -107

# social menu links

#[[social]]
#  name = "github"
#  type = "social"
#  weight = 1
#  url = "https://github.com/#"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/SprobeInc"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/company/sprobe"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
